AllCops:
  TargetRubyVersion: 3.2

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 15

Style/NumericLiterals:
  Exclude:
    - "test/dummy/db/schema.rb"
